apiVersion: v1
kind: Service
metadata:
  name: capstone-node-port
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: jenkins
      port:  80
      targetPort: 80
      nodePort: 30030
  selector:
    component: capstone-component
