apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx  #what is our ingress base
    nginx.ingress.kubernetes.io/rewrite-target: /$1 #Remove everything and write / ex: fb.com/api/authentication => fb.com/
spec:
  rules:
    - http:
        paths:
          - path: /?(.*)                                 #path recieved
            backend:
              serviceName:  capstone-cluster-ip-service #service to redirect to (hostname)
              servicePort:  80                      #operating port

