apiVersion: v1
kind: Service
metadata:
  name: jenkins-node-port
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: jenkins
      port:  8080
      targetPort: 8080
      nodePort: 30000
    - protocol: TCP
      name: discovery
      port: 50000
      targetPort: 50000
      nodePort: 30001
  selector:
    component: jenkins-component
